# Generated by Django 5.2.7 on 2025-10-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_remove_review_review_id_review_id'),
    ]

    operations = [
    ]
